export enum OrderStatus {
  PENDING_DISPATCH = 'PENDING_DISPATCH',
  DISPATCHING = 'DISPATCHING',
  ASSIGNED = 'ASSIGNED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
