apiVersion: v1
kind: ConfigMap
metadata:
  name: routefast-config
  namespace: routefast
data:
  NODE_ENV: production
  ORDER_SERVICE_URL: http://order-service:3001
  DRIVER_SERVICE_URL: http://driver-service:3002
  DISPATCH_SERVICE_URL: http://dispatch-service:3003
  TRACKING_SERVICE_URL: http://tracking-service:3004
  ORDER_SERVICE_PORT: "3001"
  DRIVER_SERVICE_PORT: "3002"
  DISPATCH_SERVICE_PORT: "3003"
  TRACKING_SERVICE_PORT: "3004"
  API_GATEWAY_PORT: "3000"
  OUTBOX_POLL_INTERVAL_MS: "500"
  OUTBOX_BATCH_SIZE: "25"
  RMQ_MAX_RETRIES: "3"
  RMQ_RETRY_DELAY_MS: "3000"
  DISPATCH_ASSIGNMENT_TIMEOUT_MS: "30000"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://adot-collector.monitoring:4318/v1/traces
  ORDER_DB_HOST: CHANGE_ME_ORDER_RDS_ENDPOINT
  DRIVER_DB_HOST: CHANGE_ME_DRIVER_RDS_ENDPOINT
  DISPATCH_DB_HOST: CHANGE_ME_DISPATCH_RDS_ENDPOINT
  TRACKING_DB_HOST: CHANGE_ME_TRACKING_RDS_ENDPOINT
  REDIS_HOST: CHANGE_ME_ELASTICACHE_ENDPOINT
  ORDER_DB_SSL: "true"
  DRIVER_DB_SSL: "true"
  DISPATCH_DB_SSL: "true"
  TRACKING_DB_SSL: "true"
  REDIS_PORT: "6379"
  REDIS_TLS: "true"
