# Copy this file to secret.yaml, replace values, and DO NOT commit the result.
apiVersion: v1
kind: Secret
metadata:
  name: routefast-secrets
  namespace: routefast
type: Opaque
stringData:
  ORDER_DB_USER: CHANGE_ME
  ORDER_DB_PASSWORD: CHANGE_ME
  ORDER_DB_NAME: routefast_orders
  DRIVER_DB_USER: CHANGE_ME
  DRIVER_DB_PASSWORD: CHANGE_ME
  DRIVER_DB_NAME: routefast_drivers
  DISPATCH_DB_USER: CHANGE_ME
  DISPATCH_DB_PASSWORD: CHANGE_ME
  DISPATCH_DB_NAME: routefast_dispatch
  TRACKING_DB_USER: CHANGE_ME
  TRACKING_DB_PASSWORD: CHANGE_ME
  TRACKING_DB_NAME: routefast_tracking
  RABBITMQ_URL: amqps://CHANGE_ME
  REDIS_PASSWORD: CHANGE_ME
